# Generated by Django 4.2.7 on 2026-06-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.AlterModelTable(
            name='user',
            table='admins',
        ),
    ]
